" Forget being compatible with good ol' vi
set nocompatible

" Add Pathogen
call pathogen#infect()
call pathogen#helptags()

" Get that filetype stuff happening
filetype on
filetype plugin on
filetype indent on

" Turn on that syntax highlighting and set background color
syntax on

" Colorscheme
" ---------------

" Solarized Settings
" let g:solarized_termcolors=256
" let g:solarized_termtrans=1
" colorscheme solarized
" set background=dark

" Gruvbox Settings
colorscheme gruvbox
set background=dark

" Dracula Settings
" let g:dracula_italic = 0
" colorscheme dracula
" highlight Normal ctermbg=None

" Remap leader
let mapleader = ","

" Seriously, guys. It's not like :W is bound to anything anyway.
command! W :w
command! Q :q
command! WQ :wq
command! Wq :wq
command! Noh :noh

" Shortcuts to make file navigation easier
cnoremap %% <C-R>=expand('%:h').'/'<cr>
map <leader>ew :e %%
map <leader>es :sp %%
map <leader>ev :vsp %%
map <leader>et :tabe %%

" Why is this not a default
set hidden

" Don't update the display while executing macros
set lazyredraw

" At least let yourself know what mode you're in
set showmode

" Show incomplete cmds down the bottom
set showcmd

" Add line numbers
set number

" Yank from the cursor to the end of the line, to be consistent with C and D.
nnoremap Y y$

if has("gui_running")
  " Highlight current line
  set cursorline
  " Highlight current column
  set cursorcolumn
  " Get rid of toolbar in MacVim
  set guioptions=aAce
  " Set font
  set guifont=Menlo:h13
end

" Set commandbar height
set cmdheight=2

" Make tab completion act more like bash
set wildmenu
set wildmode=list:longest

" Whitespace stuff
set nowrap
set tabstop=2
set shiftwidth=2
set expandtab

" Show invisible characters
" set lcs=tab:▸\ ,trail:·,eol:¬,nbsp:_
" set list

" Make omnicomplete a bit easier
imap <Leader>o <C-x><C-o>

" Searching
set hlsearch
set incsearch
set ignorecase
set smartcase

" Status Line
set statusline=%F%m%r%h%w\ [TYPE=%Y]\ \ \ \ \ \ \ \ \ \ \ \ [POS=%2l,%2v][%p%%]\ \ \ \ \ \ \ \ \ \ \ \ [LEN=%L]\ \ \ \ \ \ \ \ \ \ \ \ %{fugitive#statusline()}
set laststatus=2

" No swap files here, no sir
set nobackup
set nowritebackup
set noswapfile

" Disable error bells
set noerrorbells
set visualbell
set t_vb=

" Set Github Domains
let g:fugitive_github_domains = ['https://example.com']

" Add Handlebars support to Vim Commentary
autocmd Syntax handlebars set commentstring={{!\ %s\ }}

" Add JSX support for js files
let g:jsx_ext_required = 0

" Allow ctrlp to ignore certain directories
let g:ctrlp_custom_ignore = 'node_modules\|DS_Store\|git\|tmp'

" Toggle background color
" nmap <leader>d :let &background = ( &background == 'dark'? 'light' : 'dark' )<CR>
