# Setup Homebrew
eval $(/opt/homebrew/bin/brew shellenv)

# Setup autocompletion
if type brew &>/dev/null
then
  FPATH="$(brew --prefix)/share/zsh/site-functions:${FPATH}"
  typeset -U fpath

  autoload -Uz compinit
  compinit
fi

# Set custom prompt
setopt PROMPT_SUBST
autoload -U promptinit
promptinit

# Initialize colors
autoload -U colors
colors

# Completion settings
setopt auto_menu
setopt complete_in_word
setopt always_to_end
zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}' 'r:|[._-]=* r:|=*' 'l:|=* r:|=*'
zstyle ':completion:*' list-colors ''

# Nicer history
export HISTFILE="$HOME/.zsh_history"
export HISTSIZE=100000
export SAVEHIST=$HISTSIZE
setopt append_history
setopt extended_history
setopt hist_ignore_dups
setopt hist_ignore_space
setopt hist_verify
setopt inc_append_history
setopt share_history

# Use Vim as the editor
export EDITOR="vim"

# By default, zsh considers many characters part of a word (e.g., _ and -).
# Narrow that down to allow easier skipping through words via M-f and M-b.
export WORDCHARS='*?[]~&;!$%^<>'

# Highlight search results in ack.
export ACK_COLOR_MATCH='green'

# Customize prompt
source $HOME/.dotfiles/git/git_prompt

ZSH_THEME_GIT_PROMPT_PREFIX=""
ZSH_THEME_GIT_PROMPT_SUFFIX=""
ZSH_THEME_GIT_PROMPT_DIRTY=" !"
ZSH_THEME_GIT_PROMPT_BEHIND_REMOTE=" -"
ZSH_THEME_GIT_PROMPT_AHEAD_REMOTE=" +"
ZSH_THEME_GIT_PROMPT_DIVERGED_REMOTE=" ±"
ZSH_THEME_GIT_PROMPT_STASHED=" $"
ZSH_THEME_GIT_PROMPT_UNTRACKED="?"
local good_bad="%(?, %{$fg_bold[magenta]%}❯%{$reset_color%}, %{$fg_bold[red]%}❯%{$reset_color%})"

NEWLINE=$'\n'
PROMPT='${NEWLINE}%{$fg_bold[cyan]%}%~%{$reset_color%} %{$fg_bold[red]%}[$(rbenv version-name)]%{$reset_color%} %{$fg_bold[green]%}[$(nodenv version-name)]%{$reset_color%}${good_bad} '
RPROMPT='%{$fg_bold[yellow]%}$(git_prompt_info)$(git_prompt_status)$(git_remote_status)%{$reset_color%}'


# Setup rbenv
eval "$(rbenv init - zsh)"

# Setup nodenv
eval "$(nodenv init -)"

# Setup Postgres 16
export PATH="/opt/homebrew/opt/postgresql@16/libexec/bin:$PATH"

# https://openradar.appspot.com/27348363
# This is a fix for macOS Sierra
# -A flag adds all identities stored in keychain
ssh-add --apple-use-keychain ~/.ssh/id_ed25519 2> /dev/null
ssh-add --apple-use-keychain ~/.ssh/id_ed25519_heroku 2> /dev/null

# Source functions and aliases
source ~/.dotfiles/zsh/aliases
